import { describe, expect, test } from 'bun:test'
import { builtinTests } from '../src/tests'

describe('Built-in test registry contract', () => {
  test('number and comparison predicates cover valid and invalid values', () => {
    check('divisibleby', 12, true, 3)
    check('divisibleby', 12, false, 0)
    check('even', 12, true)
    check('even', 1.5, false)
    check('odd', 3, true)
    check('odd', 2, false)
    check('number', 1, true)
    check('number', Number.NaN, false)
    check('integer', 1, true)
    check('integer', 1.5, false)
    check('float', 1.5, true)
    check('float', Number.NaN, false)
    check('gt', 3, true, 2)
    check('ge', 3, true, 3)
    check('lt', 2, true, 3)
    check('le', 3, true, 3)
    check('greaterthan', 2, true, 1)
    check('lessthan', 1, true, 2)
  })

  test('type predicates distinguish supported JavaScript values', () => {
    check('defined', 0, true)
    check('defined', undefined, false)
    check('undefined', undefined, true)
    check('undefined', null, false)
    check('none', null, true)
    check('None', undefined, false)
    check('boolean', false, true)
    check('boolean', 0, false)
    check('string', '', true)
    check('string', [], false)
    check('mapping', { value: 1 }, true)
    check('mapping', null, false)
    check('mapping', [], false)
    check('mapping', new Date(), false)
    check('iterable', null, false)
    check('iterable', 'abc', true)
    check('iterable', [1], true)
    check('iterable', new Set([1]), true)
    check('iterable', { value: 1 }, false)
    check('sequence', [], true)
    check('sequence', 'abc', true)
    check('sequence', new Set(), false)
    check('callable', () => undefined, true)
    check('callable', {}, false)
  })

  test('string and collection predicates exercise every branch', () => {
    check('lower', 'lower', true)
    check('lower', 'Lower', false)
    check('lower', 1, false)
    check('upper', 'UPPER', true)
    check('upper', 'Upper', false)
    check('upper', 1, false)
    check('empty', null, true)
    check('empty', '', true)
    check('empty', [1], false)
    check('empty', {}, true)
    check('empty', { value: 1 }, false)
    check('empty', 0, false)
    check('in', 2, true, [1, 2])
    check('in', 'b', true, 'abc')
    check('in', 'key', true, { key: true })
    check('in', 1, false, null)
  })

  test('equality and truthiness predicates follow the runtime contract', () => {
    const reference = {}
    check('eq', 1, true, 1)
    check('ne', 1, true, 2)
    check('sameas', reference, true, reference)
    check('equalto', 1, false, '1')
    check('truthy', null, false)
    check('truthy', true, true)
    check('truthy', false, false)
    check('truthy', 0, false)
    check('truthy', 1, true)
    check('truthy', '', false)
    check('truthy', 'x', true)
    check('truthy', [], false)
    check('truthy', [1], true)
    check('truthy', {}, false)
    check('truthy', { value: 1 }, true)
    check('truthy', Symbol('value'), true)
    check('falsy', 0, true)
    check('true', true, true)
    check('true', 1, false)
    check('false', false, true)
    check('false', 0, false)
  })
})

function check(name: string, value: unknown, expected: boolean, ...args: unknown[]): void {
  const predicate = builtinTests[name]
  if (!predicate) throw new Error(`Missing built-in test: ${name}`)
  expect(predicate(value, ...args)).toBe(expected)
}
